//GUI
//creates a GUI of employee database
//Freid Tong, Hahd Khan
//November 28, 2011
package employeedatabase;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;

import javax.swing.JTextField;
import javax.swing.ButtonGroup;
/**
 * @author Freid 525983
 * @author Hahd 629195
 * 
 */
public class EmployeeGUI extends javax.swing.JFrame {

	/** Creates new form EmployeeGUI 
	 * @throws IOException */
	HashTable Database=new HashTable();

	public EmployeeGUI() throws IOException {
		initComponents();
		Database.load();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		//Initialization OF VARS
		jPanel1 = new javax.swing.JPanel();					//jpanel1 is the main panel
		btn_add = new javax.swing.JButton();				//the add button
		btn_edit = new javax.swing.JButton();				//the edit button
		btn_delete = new javax.swing.JButton();				//the delete button
		text_ID = new javax.swing.JTextField();				//the text id field
		text_fn = new javax.swing.JTextField();				//the first name text field (text fields are editable white space that you will see)
		EmpID = new javax.swing.JLabel();					//the employee Id label (labels are fields in my program which label other parts of my program I.E. the field where you write first name has a label of first name next to it)
		FirstName = new javax.swing.JLabel();				//The first name label
		MiddleName = new javax.swing.JLabel();				//The middle name label
		text_mn = new javax.swing.JTextField();				//the middle name text field
		LastName = new javax.swing.JLabel();				//the last name label
		text_ln = new javax.swing.JTextField();				//the last name text field
		WorkLocation = new javax.swing.JLabel();			//the work location label
		btn_save = new javax.swing.JButton();				//the save button 
		Enterkey = new javax.swing.JButton();				//the the save employee button
		jSeparator1 = new javax.swing.JSeparator();			//a seperator between panels
		jPanel2 = new javax.swing.JPanel();					//panel2 where all the full time buttons are 
		text_salary = new javax.swing.JTextField();			//salary text field
		Salary = new javax.swing.JLabel();					//salary label for text field
		YearsofWork = new javax.swing.JLabel();				//years of work label
		text_YW = new javax.swing.JTextField();				//years of work text field
		Vacation = new javax.swing.JLabel();				//vacation label
		text_vacation = new javax.swing.JTextField();		//vacation text field
		jPanel4 = new javax.swing.JPanel();					//panel where all the part time components are added
		text_hourlywage = new javax.swing.JTextField();		//text field for hourly wage
		Hourlywage = new javax.swing.JLabel();				//hourly wage label
		Hourweeks = new javax.swing.JLabel();				//hourly weeks  label
		text_hoursperweek = new javax.swing.JTextField();	//hours per week text field
		Weeksperyear = new javax.swing.JLabel();			//weeks per year label
		text_weeksperyear = new javax.swing.JTextField();	//weeks per year text field
		EmpID1 = new javax.swing.JLabel();					//Employee Id label
		Gender = new javax.swing.JLabel();					//Employee Gender Label
		jScrollPane1 = new javax.swing.JScrollPane();		//Scroll Panel
		text_instruct = new javax.swing.JTextArea();		//Area where instructions are outputted
		btn_search = new javax.swing.JButton();				//search button 
		Male = new javax.swing.JRadioButton();				//male radio button
		Mississauga = new javax.swing.JRadioButton();		//Mississauga radio button
		Female = new javax.swing.JRadioButton();			//female radio button
		Ottawa = new javax.swing.JRadioButton();			//Ottawa radio button
		Regina = new javax.swing.JRadioButton();			//Regina radio button
		Fulltime = new javax.swing.JRadioButton();			//Full time radio button
		Parttime = new javax.swing.JRadioButton();			//part time radio button
		Clear = new javax.swing.JButton();					//clear button
		text_dr2 = new javax.swing.JTextField();			//deduction rate text field
		DeductRate2 = new javax.swing.JLabel();				//deduction rate label
		btn_load = new javax.swing.JButton();				//load button
		btn_close = new javax.swing.JButton();				//close button

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);// close operation set to exit on close
		setTitle("Employee Database");										// Employee database title of window
		setLocationByPlatform(true);										// location dependent on platform (random on screen)
		setResizable(false);												// Window cannot be resized (so button are not messed)
		setUndecorated(true);												// undecorated factor is true

		jPanel1.setBackground(new java.awt.Color(193, 179, 179));			//sets background colour
		jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));// sets border colour
		jPanel1.setToolTipText("Employee DataBase");									

		btn_add.setBackground(new java.awt.Color(51, 255, 51));				//color set for add button
		btn_add.setText("Add");												//labeled as "Add"
		btn_add.addActionListener(new java.awt.event.ActionListener() {		//action listener
			public void actionPerformed(java.awt.event.ActionEvent evt) {	// listens to Add event
				btn_addActionPerformed(evt);
			}
		});
		//similar to add button
		btn_edit.setBackground(new java.awt.Color(255, 255, 0));
		btn_edit.setText("Edit");
		btn_edit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_editActionPerformed(evt);
			}
		});
		//similar to add button
		btn_delete.setBackground(new java.awt.Color(255, 0, 0));
		btn_delete.setText("Delete");
		btn_delete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_deleteActionPerformed(evt);
			}
		});
		//default status of components
		text_ID.setEditable(true);			
		text_ID.setText("Enter ID");

		text_fn.setEditable(false);
		text_fn.setText("Enter First Name");

		EmpID.setBackground(new java.awt.Color(204, 204, 204));
		EmpID.setText("Emp Id");

		FirstName.setBackground(new java.awt.Color(204, 204, 204));
		FirstName.setText("First Name");

		MiddleName.setBackground(new java.awt.Color(204, 204, 204));
		MiddleName.setText("Middle Name");

		text_mn.setEditable(false);
		text_mn.setText("Enter Middle Name");

		LastName.setBackground(new java.awt.Color(204, 204, 204));
		LastName.setText("Last Name");

		text_ln.setEditable(false);
		text_ln.setText("Enter Last Name");

		WorkLocation.setBackground(new java.awt.Color(204, 204, 204));
		WorkLocation.setText("Work Location");
		//similar to add button
		btn_save.setBackground(new java.awt.Color(0, 255, 255));
		btn_save.setText("Save");
		btn_save.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btn_saveActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		//similar to enterkey button
		Enterkey.setBackground(new java.awt.Color(204, 204, 255));
		Enterkey.setText("Save Employee Data");
		Enterkey.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				EnterkeyActionPerformed(evt);
			}
		});
		//default status of components in full time
		jPanel2.setBackground(new java.awt.Color(255, 255, 153));
		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.cyan, java.awt.Color.cyan));

		text_salary.setEditable(false);
		text_salary.setText("Enter Salary");

		Salary.setBackground(new java.awt.Color(204, 204, 204));
		Salary.setText("Salary");

		YearsofWork.setBackground(new java.awt.Color(204, 204, 204));
		YearsofWork.setText("Years of Work");

		text_YW.setEditable(false);
		text_YW.setText("Enter Years of Work");

		Vacation.setBackground(new java.awt.Color(204, 204, 204));
		Vacation.setText("#Vacation Days");

		text_vacation.setEditable(false);
		text_vacation.setText("Enter vacation days");
		//resizing and movement/layout of all components in the Jpanel 2 (the panel where all of full time stuff is)
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		//focuses on relative horizontal movement
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addGap(49, 49, 49)
														.addComponent(Salary))
														.addComponent(YearsofWork))
														.addGap(18, 18, 18)
														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addComponent(text_YW)
																.addComponent(text_salary, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
																.addGroup(jPanel2Layout.createSequentialGroup()
																		.addComponent(Vacation)
																		.addGap(18, 18, 18)
																		.addComponent(text_vacation)))
																		.addContainerGap(54, Short.MAX_VALUE))
		);
		//focuses on relative vertical movement
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Salary)
								.addComponent(text_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(YearsofWork)
										.addComponent(text_YW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Vacation)
												.addComponent(text_vacation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(29, Short.MAX_VALUE))
		);
		//default status of components in part time (jpanel4 )
		jPanel4.setBackground(new java.awt.Color(255, 153, 153));
		jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, null, java.awt.Color.white, java.awt.Color.cyan));

		text_hourlywage.setEditable(false);
		text_hourlywage.setText("Enter Hourly wage");

		Hourlywage.setBackground(new java.awt.Color(204, 204, 204));
		Hourlywage.setText("Hourly Wage");

		Hourweeks.setBackground(new java.awt.Color(204, 204, 204));
		Hourweeks.setText("Hours per Week");

		text_hoursperweek.setEditable(false);
		text_hoursperweek.setText("Enter Hours/Week");

		Weeksperyear.setBackground(new java.awt.Color(204, 204, 204));
		Weeksperyear.setText("Weeks per Year");

		text_weeksperyear.setEditable(false);
		text_weeksperyear.setText("Enter Weeks /Year");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		//resizing and movement/layout of all components in the Jpanel 4 (the panel where all of part time stuff is)
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				//focuses on relative horizontal movement
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(Hourlywage)
								.addComponent(Hourweeks)
								.addComponent(Weeksperyear))
								.addGap(20, 20, 20)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(text_weeksperyear, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
										.addComponent(text_hoursperweek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
										.addComponent(text_hourlywage, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(82, 82, 82))
		);
		jPanel4Layout.setVerticalGroup(
				//focuses on relative vertical movement
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Hourlywage)
								.addComponent(text_hourlywage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(Hourweeks)
										.addComponent(text_hoursperweek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Weeksperyear)
												.addComponent(text_weeksperyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(31, Short.MAX_VALUE))
		);
		//default status of components in main panel where rest of the stuff is
		EmpID1.setBackground(new java.awt.Color(204, 204, 204));
		EmpID1.setText("Instructions");

		Gender.setBackground(new java.awt.Color(204, 204, 204));
		Gender.setText("Gender");

		text_instruct.setColumns(20);
		text_instruct.setEditable(false);
		text_instruct.setRows(5);
		text_instruct.setText("Instructions for Add, Edit and Delete\nbutton event will be posted here.\n\nError Descriptions will be posted here");
		jScrollPane1.setViewportView(text_instruct);
		//similar to add button
		btn_search.setBackground(new java.awt.Color(204, 204, 255));
		btn_search.setText("Search");
		btn_search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_searchActionPerformed(evt);
			}
		});
		//similar to add button
		Male.setText("Male");	
		Male.setEnabled(true);
		Male.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MaleActionPerformed(evt);
			}
		});
		//similar to add button
		Mississauga.setText("Mississauga");
		Mississauga.setEnabled(true);
		Mississauga.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MississaugaActionPerformed(evt);
			}
		});
		//similar to add button
		Female.setText("Female");
		Female.setEnabled(true);
		Female.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FemaleActionPerformed(evt);
			}
		});
		//similar to add button
		Ottawa.setText("Ottawa");
		Ottawa.setEnabled(true);
		Ottawa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OttawaActionPerformed(evt);
			}
		});
		//similar to add button
		Regina.setText("Regina");
		Regina.setEnabled(true);
		Regina.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ReginaActionPerformed(evt);
			}
		});
		//similar to add button
		Fulltime.setText("Full Time");
		Fulltime.setEnabled(true);
		Fulltime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FulltimeActionPerformed(evt);
			}
		});
		//similar to add button
		Parttime.setText("Part Time");
		Parttime.setEnabled(true);
		Parttime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ParttimeActionPerformed(evt);
			}
		});
		//similar to add button
		Clear.setBackground(new java.awt.Color(153, 255, 204));
		Clear.setText("Clear");
		Clear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ClearActionPerformed(evt);
			}
		});

		text_dr2.setEditable(false);
		text_dr2.setText("Enter Deductions Rate");

		DeductRate2.setBackground(new java.awt.Color(204, 204, 204));
		DeductRate2.setText("Deductions Rate");
		//similar to add button
		btn_load.setBackground(new java.awt.Color(0, 255, 255));
		btn_load.setText("Clear Database");
		btn_load.addActionListener(new java.awt.event.ActionListener() {

			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_loadActionPerformed(evt);
			}
		});
		//similar to add button
		btn_close.setBackground(new java.awt.Color(255, 51, 51));
		btn_close.setText("X");
		btn_close.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btn_closeActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		//layout of main panel where everything is
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				//focuses on horizontal spacing
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(EmpID)
														.addGap(36, 36, 36)
														.addComponent(text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
														.addComponent(btn_search)
														.addGap(30, 30, 30))
														.addComponent(EmpID1)
														.addComponent(Gender)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(MiddleName)
																		.addComponent(FirstName))
																		.addGap(18, 18, 18)
																		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(text_fn, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
																				.addComponent(text_ln, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
																				.addComponent(text_mn, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
																				.addComponent(LastName)
																				.addGroup(jPanel1Layout.createSequentialGroup()
																						.addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(btn_delete)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
																						.addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(Enterkey))
																						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
																						.addGroup(jPanel1Layout.createSequentialGroup()
																								.addComponent(Mississauga)
																								.addGap(58, 58, 58)
																								.addComponent(Ottawa)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
																								.addComponent(Regina)
																								.addGap(12, 12, 12))
																								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																										.addComponent(Male)
																										.addComponent(WorkLocation)))
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																										.addGroup(jPanel1Layout.createSequentialGroup()
																												.addComponent(Female)
																												.addGap(83, 83, 83)))
																												.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(jPanel1Layout.createSequentialGroup()
																																.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																																.addContainerGap())
																																.addGroup(jPanel1Layout.createSequentialGroup()
																																		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addComponent(Parttime))
																																				.addContainerGap())
																																				.addGroup(jPanel1Layout.createSequentialGroup()
																																						.addComponent(Fulltime)
																																						.addContainerGap())
																																						.addGroup(jPanel1Layout.createSequentialGroup()
																																								.addGap(90, 90, 90)
																																								.addComponent(btn_load)
																																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																								.addComponent(btn_save)
																																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																								.addComponent(btn_close)
																																								.addGap(7, 7, 7))
																																								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																																										.addGap(12, 12, 12)
																																										.addComponent(DeductRate2)
																																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
																																										.addComponent(text_dr2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addGap(39, 39, 39))))
		);
		//focuses on vertical spacing
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btn_load)
												.addComponent(btn_save)
												.addComponent(btn_close))
												.addGap(8, 8, 8)
												.addComponent(Fulltime)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(87, 87, 87)
												.addComponent(Parttime)
												.addGap(1, 1, 1)
												.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(46, 46, 46)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(text_dr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(DeductRate2)))
														.addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
														.addContainerGap())
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addGap(22, 22, 22)
																				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(EmpID)
																						.addComponent(text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGap(8, 8, 8)
																						.addComponent(EmpID1))
																						.addGroup(jPanel1Layout.createSequentialGroup()
																								.addContainerGap(22, 22)
																								.addComponent(btn_search)))
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(btn_add)
																										.addComponent(btn_edit)
																										.addComponent(btn_delete)
																										.addComponent(Enterkey)
																										.addComponent(Clear))
																										.addGap(18, 18, 18)
																										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(FirstName)
																												.addComponent(text_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGap(18, 18, 18)
																												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(MiddleName)
																														.addComponent(text_mn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGap(18, 18, 18)
																														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(LastName)
																																.addComponent(text_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(Gender)
																																.addGap(29, 29, 29)
																																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																		.addComponent(Female)
																																		.addComponent(Male))
																																		.addGap(18, 18, 18)
																																		.addComponent(WorkLocation)
																																		.addGap(34, 34, 34)
																																		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																				.addComponent(Mississauga)
																																				.addComponent(Regina)
																																				.addComponent(Ottawa))
																																				.addGap(41, 41, 41))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 696, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 542, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		getAccessibleContext().setAccessibleDescription("");
		getAccessibleContext().setAccessibleParent(btn_close);

		pack();
	}// </editor-fold>
	public float numreader(JTextField e)		//numreader is a procedure which reads sting values and converts them to float values
	{
		float num;
		String getvalue;
		getvalue=e.getText();
		num=Float.valueOf(getvalue);
		return num;
	}
	public int intreader(JTextField e)			//intreader is a procedure which reads sting values and converts them to integer values
	{
		int num;
		String getvalue;
		getvalue=e.getText();
		num=Integer.parseInt(getvalue);
		return num;
	}
	private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {   //add button events performed in it                                    
		Object source=evt.getSource();										//event getter					
		adding=true;														//adding will be true
		editing=false;														//editing will be false
		if(source==btn_add)													//add button
		{
			//following radio buttons enabled
			Male.setEnabled(true);													
			Female.setEnabled(true);
			Mississauga.setEnabled(true);
			Ottawa.setEnabled(true);
			Regina.setEnabled(true);
			Fulltime.setEnabled(true);
			Parttime.setEnabled(true);
			//tell text box what to say
			text_instruct.setText("Enter All Employee Fields and press enter once finished.To enable disabled fields of Part time or full time be sure to check type of Employee");
			//emptying all fields
			text_fn.setText("");
			text_ID.setText(String.valueOf(Database.generateEmpNumber()));
			text_fn.setText("");
			text_ln.setText("");
			text_mn.setText("");
			text_salary.setText("");
			text_vacation.setText("");
			text_weeksperyear.setText("");
			text_hourlywage.setText("");   
			text_hoursperweek.setText("");
			text_YW.setText(""); 
			text_dr2.setText("");
			//following fields are editable (true) or non editable (false) 
			text_fn.setEditable(true);
			text_ID.setEditable(true);
			text_fn.setEditable(true);
			text_ln.setEditable(true);
			text_mn.setEditable(true);
			text_salary.setEditable(false);
			text_vacation.setEditable(false);
			text_weeksperyear.setEditable(false);
			text_hourlywage.setEditable(false);
			text_hoursperweek.setEditable(false);
			text_YW.setEditable(false);
			text_dr2.setEditable(true);
			//follwing fields are not selected
			Fulltime.setSelected(false);
			Parttime.setSelected(false);
			Mississauga.setSelected(false);
			Ottawa.setSelected(false);
			Regina.setSelected(false);
			Male.setSelected(false);
			Female.setSelected(false);
		} 
	}                                       

	private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {                                         
		editing=true;
		adding=false;
		//following text fields are enabled
		Male.setEnabled(true);
		Female.setEnabled(true);
		Mississauga.setEnabled(true);
		Ottawa.setEnabled(true);
		Regina.setEnabled(true);
		Fulltime.setEnabled(true);
		Parttime.setEnabled(true);
		text_instruct.setText("Please search for the employee ID of the employee whose information you wish to edit. ");
		text_ID.setEditable(true);
		text_fn.setEditable(true);
		text_ID.setEditable(true);
		text_fn.setEditable(true);
		text_ln.setEditable(true);
		text_mn.setEditable(true);
		text_dr2.setEditable(true);
		if (Fulltime.isSelected()) //gets selected for fulltime
		{	
			//sets following fields editable
			text_salary.setEditable(true);
			text_vacation.setEditable(true);

			text_YW.setEditable(true);
			//sets following fields non editable
			text_hourlywage.setEditable(false);
			text_hoursperweek.setEditable(false);
			text_weeksperyear.setEditable(false);
			ftime=true;
			ptime=false;

		}
		else if (Parttime.isSelected())//vice versa the above if action
		{
			text_salary.setEditable(false);
			text_vacation.setEditable(false);

			text_YW.setEditable(false);
			text_hourlywage.setEditable(true);
			text_hoursperweek.setEditable(true);
			text_weeksperyear.setEditable(true);
			ptime=true;
			ftime=false;


		}

	}                                        

	private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {   //deletes employee                                        
		editing=false;
		adding=false;
		ptime=false;
		ftime=false;
		text_ID.setEditable(true);
		try
		{
			Database.remove(intreader(text_ID));
		}
		catch (NumberFormatException e)
		{
			text_instruct.setText("Invalid ID");
		}
		text_fn.setText("");
		text_ID.setText("");
		text_fn.setText("");
		text_ln.setText("");
		text_mn.setText("");
		text_salary.setText("");
		text_vacation.setText("");
		text_weeksperyear.setText("");
		text_hourlywage.setText("");   
		text_hoursperweek.setText("");
		text_YW.setText(""); 
		text_dr2.setText("");
		text_fn.setEditable(true);
		text_fn.setEditable(true);
		text_ln.setEditable(true);
		text_mn.setEditable(true);
		text_salary.setEditable(false);
		text_vacation.setEditable(false);
		text_weeksperyear.setEditable(false);
		text_hourlywage.setEditable(false);
		text_hoursperweek.setEditable(false);
		text_YW.setEditable(false);
		text_dr2.setEditable(true);

		Fulltime.setSelected(false);
		Parttime.setSelected(false);
		Mississauga.setSelected(false);
		Ottawa.setSelected(false);
		Regina.setSelected(false);
		Male.setSelected(false);
		Female.setSelected(false);

	}                                          

	private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) throws IOException 
	{                                         
		Database.save();//saves database
	}                                        

	private void EnterkeyActionPerformed(java.awt.event.ActionEvent evt) {          //save employee button                               
		if (editing==true)
		{
			Database.remove(intreader(text_ID));									//if editing the person then he's removed first then added later
		}

		if ((adding||editing)&& ftime)												//adding or editing has to be true and full time has to be true
		{

			FullTimeEmployee FT= new FullTimeEmployee();
			try 

			{
				EmployeeID=intreader(text_ID);
				FT.setEmpNumber(EmployeeID);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for Employeed ID");
			}

			Sfirstname=text_fn.getText();
			FT.setFirstName(Sfirstname);
			Smiddlename=text_mn.getText();
			FT.setMiddleName(Smiddlename);
			Slastname=text_ln.getText();
			FT.setLastName(Slastname);

			try
			{    
				deductionrate=numreader(text_dr2);
				FT.setDeductionsRate (deductionrate);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for field deduction rate in part time");
			}
			try
			{

				salary=intreader(text_salary);
				FT.setSalary(salary);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid number for field Salary");
			}
			try
			{
				yearsofwork=intreader(text_YW);
				FT.setYearsOfService(yearsofwork);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for field Yearly Work");
			}
			try
			{
				vacationdays=intreader(text_vacation);
				FT.setDaysVacPerYear(vacationdays);
			}

			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for field Vacation");
			}
			if (Mississauga.isSelected())
			{
				FT.setWorkLocation("Mississauga");
			}
			else if (Regina.isSelected())
			{
				FT.setWorkLocation("Regina");
			}
			else if (Ottawa.isSelected())
			{
				FT.setWorkLocation("Ottawa");
			}
			if (Male.isSelected())
			{
				FT.setSex(true);
			}
			else if (Female.isSelected())
			{
				FT.setSex(false);
			}


			Database.addFull(FT);
			text_fn.setText("");
			text_ID.setText("");
			text_fn.setText("");
			text_ln.setText("");
			text_mn.setText("");
			text_salary.setText("");
			text_vacation.setText("");
			text_weeksperyear.setText("");
			text_hourlywage.setText("");   
			text_hoursperweek.setText("");
			text_YW.setText(""); 
			text_dr2.setText("");

			//make all following field noneditable
			text_fn.setEditable(false);
			text_fn.setEditable(false);
			text_ln.setEditable(false);
			text_mn.setEditable(false);
			text_salary.setEditable(false);
			text_vacation.setEditable(false);
			text_weeksperyear.setEditable(false);
			text_hourlywage.setEditable(false);
			text_hoursperweek.setEditable(false);
			text_YW.setEditable(false);
			text_dr2.setEditable(false);

			Fulltime.setSelected(false);
			Parttime.setSelected(false);
			Mississauga.setSelected(false);
			Ottawa.setSelected(false);
			Regina.setSelected(false);
			Male.setSelected(false);
			Female.setSelected(false);
			adding=false;
			editing=false;
			ftime=false;
			ptime=false;

		}
		else if ((adding||editing)&& ptime)
		{



			PartTimeEmployee PT= new PartTimeEmployee();


			try 
			{
				EmployeeID=intreader(text_ID);
				PT.setEmpNumber(EmployeeID);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for Employeed ID");
			}

			Sfirstname=text_fn.getText();
			PT.setFirstName(Sfirstname);
			Smiddlename=text_mn.getText();
			PT.setMiddleName(Smiddlename);
			Slastname=text_ln.getText();
			PT.setLastName(Slastname);

			try
			{    
				deductionrate=numreader(text_dr2);
				PT.setDeductionsRate (deductionrate);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for field deduction rate in part time");
			}
			try
			{
				hourlywage=numreader(text_hourlywage);
				PT.setHourlyWage(hourlywage);

			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for hourly wage");
			}
			try
			{
				hoursperweek=intreader(text_hoursperweek);
				PT.setHrsPerWeek(hoursperweek);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for hours for week");
			}
			try
			{

				weeksperyear=intreader(text_weeksperyear);
				PT.setWeeksPerYear(weeksperyear);
			}
			catch (NumberFormatException e)
			{
				text_instruct.append("\n");
				text_instruct.append("Please Enter a Valid integer for Employeed ID");
			}
			if (Mississauga.isSelected())
			{
				PT.setWorkLocation("Mississauga");
			}
			else if (Regina.isSelected())
			{
				PT.setWorkLocation("Regina");
			}
			else if (Ottawa.isSelected())
			{
				PT.setWorkLocation("Ottawa");
			}
			if (Male.isSelected())
			{
				PT.setSex(true);
			}
			else if (Female.isSelected())
			{
				PT.setSex(false);
			}

			Database.addPart(PT);

			text_fn.setText("");
			text_ID.setText("");
			text_fn.setText("");
			text_ln.setText("");
			text_mn.setText("");
			text_salary.setText("");
			text_vacation.setText("");
			text_weeksperyear.setText("");
			text_hourlywage.setText("");   
			text_hoursperweek.setText("");
			text_YW.setText(""); 
			text_dr2.setText("");

			text_fn.setEditable(false);
			text_fn.setEditable(false);
			text_ln.setEditable(false);
			text_mn.setEditable(false);
			text_salary.setEditable(false);
			text_vacation.setEditable(false);
			text_weeksperyear.setEditable(false);
			text_hourlywage.setEditable(false);
			text_hoursperweek.setEditable(false);
			text_YW.setEditable(false);
			text_dr2.setEditable(false);

			Fulltime.setSelected(false);
			Parttime.setSelected(false);
			Mississauga.setSelected(false);
			Ottawa.setSelected(false);
			Regina.setSelected(false);
			Male.setSelected(false);
			Female.setSelected(false);

			adding=false;
			editing=false;
			ftime=false;
			ptime=false;

		}

	}                                        

	private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {                                           
		try
		{
			int temp = intreader(text_ID);

			try
			{
				try
				{
					FullTimeEmployee tempFull = (FullTimeEmployee) Database.findEmployee(temp);
					text_fn.setText(tempFull.getFirstName());
					text_mn.setText(tempFull.getMiddleName());
					text_ln.setText(tempFull.getLastName());
					Fulltime.setSelected(true);
					Male.setSelected(tempFull.isSex());
					Female.setSelected(!tempFull.isSex());
					if (tempFull.getWorkLocation().equals("Mississauga"))
					{
						Mississauga.setSelected(true);
						Ottawa.setSelected(false);
						Regina.setSelected(false);
					}
					else if (tempFull.getWorkLocation().equals("Regina"))
					{
						Mississauga.setSelected(false);
						Ottawa.setSelected(false);
						Regina.setSelected(true);
					}
					else if (tempFull.getWorkLocation().equals("Ottawa"))
					{
						Mississauga.setSelected(false);
						Ottawa.setSelected(true);
						Regina.setSelected(false);
					}
					int gross=tempFull.getSalary();
					double net=gross-(gross*(tempFull.getDeductionsRate()));
					ftime=true;
					text_salary.setText(String.valueOf(tempFull.getSalary()));
					text_vacation.setText(String.valueOf(tempFull.getDaysVacPerYear()));
					text_YW.setText(String.valueOf(tempFull.getYearsOfService()));
					text_dr2.setText(String.valueOf(tempFull.getDeductionsRate()));
					text_instruct.setText("Employee's Gross:"+String.valueOf(gross));
					text_instruct.append("\n");
					text_instruct.append("Employee's Net:"+Math.round(net*100)/100.0);

				}
				catch (ClassCastException e)
				{
					PartTimeEmployee tempPart = (PartTimeEmployee) Database.findEmployee(temp);
					ptime=true;
					text_fn.setText(tempPart.getFirstName());
					text_mn.setText(tempPart.getMiddleName());
					text_ln.setText(tempPart.getLastName());
					Parttime.setSelected(true);
					Male.setSelected(tempPart.isSex());
					Female.setSelected(!tempPart.isSex());
					if (tempPart.getWorkLocation().equals("Mississauga"))
					{
						Mississauga.setSelected(true);
						Ottawa.setSelected(false);
						Regina.setSelected(false);
					}
					else if (tempPart.getWorkLocation().equals("Regina"))
					{
						Mississauga.setSelected(false);
						Ottawa.setSelected(false);
						Regina.setSelected(true);
					}
					else if (tempPart.getWorkLocation().equals("Ottawa"))
					{
						Mississauga.setSelected(false);
						Ottawa.setSelected(true);
						Regina.setSelected(false);
					}

					double gross=tempPart.getWeeksPerYear()*tempPart.getHourlyWage()*tempPart.getHrsPerWeek();
					double net=gross-(gross*(tempPart.getDeductionsRate()));
					text_instruct.setText("Employee's Gross:"+String.valueOf(gross));
					text_instruct.append("\n");
					text_instruct.append("Employee's Net:"+Math.round(net*100)/100.0);

					text_weeksperyear.setText(String.valueOf(tempPart.getWeeksPerYear()));
					text_hourlywage.setText(String.valueOf(tempPart.getHourlyWage()));
					text_hoursperweek.setText(String.valueOf(tempPart.getHrsPerWeek()));
					text_dr2.setText(String.valueOf(tempPart.getDeductionsRate()));


				}
			}
			catch (NullPointerException e)
			{
				text_instruct.setText("Employee Not Found, Please Enter an Existing Employee ID");

			}
		}
		catch(NumberFormatException e)
		{
			text_instruct.setText("Please Enter a Valid Employee ID");
		}

	}

	private void MaleActionPerformed(java.awt.event.ActionEvent evt) {                                     
		Female.setSelected(false);
		male=true;
		female=false;
	}                                    

	private void FemaleActionPerformed(java.awt.event.ActionEvent evt) { 
		Male.setSelected(false);
		female=true;
		male=false;// TODO add your handling code here:
	}                                      

	private void MississaugaActionPerformed(java.awt.event.ActionEvent evt) {  
		Ottawa.setSelected(false);
		Regina.setSelected(false);

		mississaugas=true;
		ottawas=false;// TODO add your handling code here:
		reginas=false;
	}                                           

	private void OttawaActionPerformed(java.awt.event.ActionEvent evt) {  
		Mississauga.setSelected(false);
		Regina.setSelected(false);

		mississaugas=false;
		ottawas=true;// TODO add your handling code here:
		reginas=false;
	}                                      

	private void ReginaActionPerformed(java.awt.event.ActionEvent evt) {                                       
		Mississauga.setSelected(false);
		Ottawa.setSelected(false);

		mississaugas=false;
		ottawas=false;// TODO add your handling code here:
		reginas=true;
	}                                      

	private void FulltimeActionPerformed(java.awt.event.ActionEvent evt) {   
		Parttime.setSelected(false);
		ftime=true;
		ptime=false;

		text_salary.setEditable(true);
		text_vacation.setEditable(true);
		text_YW.setEditable(true);
		text_weeksperyear.setEditable(false);
		text_hourlywage.setEditable(false);
		text_hoursperweek.setEditable(false);
		text_dr2.setEditable(true);
	}                                        

	private void ParttimeActionPerformed(java.awt.event.ActionEvent evt) {      
		Fulltime.setSelected(false);
		ftime=false;
		ptime=true;

		text_salary.setEditable(false);
		text_vacation.setEditable(false);
		text_YW.setEditable(false);
		text_weeksperyear.setEditable(true);
		text_hourlywage.setEditable(true);
		text_hoursperweek.setEditable(true);
		text_dr2.setEditable(true);// TODO add your handling code here:
	}                                        

	private void ClearActionPerformed(java.awt.event.ActionEvent evt) {                                      
		text_instruct.setText("");
		text_ID.setText("Enter ID");
		text_ID.setEditable(true);
		text_fn.setText("Enter First Name");
		text_fn.setEditable(true);
		text_mn.setText("Enter Middle Name");
		text_mn.setEditable(true);
		text_ln.setText("Enter Last Name");
		text_ln.setEditable(true);
		Mississauga.setSelected(false);
		Ottawa.setSelected(false);
		Regina.setSelected(false);
		mississaugas=false;
		reginas=false;
		ottawas=false;
		Male.setSelected(false);
		Female.setSelected(false);
		Parttime.setSelected(false);
		Fulltime.setSelected(false);
		text_salary.setEditable(true);
		text_salary.setText("Enter Salary");
		text_vacation.setEditable(true);
		text_vacation.setText("Enter Vacation Days");
		text_YW.setEditable(true);
		text_YW.setText("Enter Years Worked");
		text_weeksperyear.setEditable(true);
		text_weeksperyear.setText("Enter Weeks/Year");
		text_hourlywage.setEditable(true);
		text_hourlywage.setText("Enter Hourly Wage");
		text_hoursperweek.setEditable(true);
		text_hoursperweek.setText("Enter Hours/Week");
		text_dr2.setEditable(true);
		text_dr2.setText("Enter Deductions Rate");
		ftime=false;
		ptime=false;

	}                                     
	public void pullThePlug() {
		WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
		Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
	}
	public void minimize(){
		WindowEvent mini=new WindowEvent(this, WindowEvent.WINDOW_ICONIFIED);
		Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(mini);
	}
	private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {                                          
		minimize();
		Database.clear();
		text_instruct.setText("Database Cleared");
	}                                         


	private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                          
		Database.save();
		pullThePlug(); 
	}                                         


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {

				try {
					new EmployeeGUI().setVisible(true);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

	}
	private String Sfirstname;
	private String Smiddlename;
	private String Slastname;
	private int EmployeeID;
	private float deductionrate;
	private int salary;
	private int yearsofwork;
	private int vacationdays;
	private float hourlywage;
	private int hoursperweek;
	private int weeksperyear;
	private boolean male;
	private boolean female;
	private boolean ftime=false;
	private boolean ptime=false;
	private boolean mississaugas=false;
	private boolean reginas=false;
	private boolean ottawas=false;
	private boolean adding=false;
	private boolean editing=false;
	// Variables declaration - do not modify
	private javax.swing.JButton Clear;
	private javax.swing.JLabel DeductRate2;
	private javax.swing.JLabel EmpID;
	private javax.swing.JLabel EmpID1;
	private javax.swing.JButton Enterkey;
	private javax.swing.JRadioButton Female;
	private javax.swing.JLabel FirstName;
	private javax.swing.JRadioButton Fulltime;
	private javax.swing.JLabel Gender;
	private javax.swing.JLabel Hourlywage;
	private javax.swing.JLabel Hourweeks;
	private javax.swing.JLabel LastName;
	private javax.swing.JRadioButton Male;
	private javax.swing.JLabel MiddleName;
	private javax.swing.JRadioButton Mississauga;
	private javax.swing.JRadioButton Ottawa;
	private javax.swing.JRadioButton Parttime;
	private javax.swing.JRadioButton Regina;
	private javax.swing.JLabel Salary;
	private javax.swing.JLabel Vacation;
	private javax.swing.JLabel Weeksperyear;
	private javax.swing.JLabel WorkLocation;
	private javax.swing.JLabel YearsofWork;
	private javax.swing.JButton btn_add;
	private javax.swing.JButton btn_close;
	private javax.swing.JButton btn_delete;
	private javax.swing.JButton btn_edit;
	private javax.swing.JButton btn_load;
	private javax.swing.JButton btn_save;
	private javax.swing.JButton btn_search;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField text_ID;
	private javax.swing.JTextField text_YW;
	private javax.swing.JTextField text_dr2;
	private javax.swing.JTextField text_fn;
	private javax.swing.JTextField text_hourlywage;
	private javax.swing.JTextField text_hoursperweek;
	private javax.swing.JTextArea text_instruct;
	private javax.swing.JTextField text_ln;
	private javax.swing.JTextField text_mn;
	private javax.swing.JTextField text_salary;
	private javax.swing.JTextField text_vacation;
	private javax.swing.JTextField text_weeksperyear;
	// End of variables declaration
}
